# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Install linux deps
      run: |
        sudo apt-get update
        sudo apt-get -y install ffmpeg
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: cache-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
            cache-${{ runner.os }}-go-

    - name: Run coverage
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

